INSERT INTO category (catAbbr, catName)
VALUES
	("ARS", "Academic Recovery Seminar"),
	("ACC", "Accounting"),
	("IAA", "Advanced Data Analytics"),
	("ADS", "African American and African Diaspora Studies"),
	("ASL", "American Sign Language"),
	("ATY", "Anthropology"),
	("APD", "Apparel Product Design"),
	("ARB", "Arabic"),
	("ARC", "Archaeology"),
	("ART", "Art"),
	("ARE", "Art Education"),
	("ARH", "Art History"),
	("AAD", "Arts Administration"),
	("AST", "Astronomy"),
	("IAB", "Bioinformatics"),
	("BIO", "Biology"),
	("BUS", "Business Administration"),
	("CHE", "Chemistry and Biochemistry"),
	("CHI", "Chinese"),
	("CCI", "Classical Civilization"),
	("CSD", "Communication Sciences and Disorders"),
	("CST", "Communication Studies"),
	("CTR", "Community and Therapeutic Recreation"),
	("CTP", "Comprehensive Transition and Postsecondary Education"),
	("IAC", "Computational Analytics"),
	("CSC", "Computer Science"),
	("CNS", "Consortium"),
	("CRS", "Consumer, Apparel, and Retail Studies"),
	("CED", "Counseling and Educational Development"),
	("IAL", "Cultural Analytics"),
	("DCE", "Dance"),
	("ECO", "Economics"),
	("ELC", "Educational Leadership and Cultural Foundations"),
	("ERM", "Educational Research Methodology"),
	("ENG", "English"),
	("ENT", "Entrepeneurship"),
	("FIN", "Finance"),
	("FYE", "First Year Experience"),
	("FFL", "Foundations for Learning"),
	("FRE", "French"),
	("FMS", "Freshman Seminars Programs"),
	("GEN", "Genetic Counseling"),
	("GES", "Geography, Environment, and Sustainability"),
	("IAG", "Geospatioal Analytics"),
	("GER", "German"),
	("GRO", "Gerontology"),
	("GRK", "Greek"),
	("IAH", "Health Informatics"),
	("HED", "Higher Education"),
	("HIS", "History"),
	("HSS", "Honors Programs"),
	("HTM", "Hospitality and Tourism Management"),
	("HDF", "Human Development and Family Studies"),
	("BLS", "Humanities"),
	("IAF", "Informatics and Analytics Foundations"),
	("IST", "Information Science"),
	("ISM", "Information Systems and Operations Management"),
	("IPS", "Integrated Professional Studies"),
	("ISL", "Integrated Studies Lab"),
	("IAR", "Interior Architecture"),
	("ITL", "Intelink"),
	("IGS", "International and Global Studies"),
	("ISE", "International Student Exchange"),
	("ITA", "Italian"),
	("JNS", "Japanese Studies"),
	("KIN", "Kinesiology"),
	("KOR", "Korean"),
	("LLC", "Languages, Literatures, and Cultures"),
	("LAT", "Latin"),
	("LIS", "Library and Information Science"),
	("MGT", "Management"),
	("MKT", "Marketing"),
	("MAS", "Master of Applied Arts and Sciences"),
	("MBA", "Master of Business Administration"),
	("MAT", "Mathematics"),
	("MST", "Media Studies"),
	("MCP", "Middle College"),
	("MSC", "Military Science"),
	("MUE", "Music Education"),
	("ENS", "Music Ensemble"),
	("MUP", "Music Performance"),
	("MUS", "Music Studies"),
	("NAN", "Nanoscience"),
	("NUR", "Nursing"),
	("NTR", "Nutrition"),
	("ONC", "Online NC Interinstitutional"),
	("PCS", "Peace and Conflict Studies"),
	("PHI", "Philosophy"),
	("PHY", "Physics"),
	("PSC", "Political Science"),
	("PSY", "Psychology"),
	("HEA", "Public Health"),
	("REL", "Religious Studies"),
	("RCO", "Residential College"),
	("RCS", "Retailing and Consumer Studies"),
	("RUS", "Russian"),
	("HHS", "School of Health and Human Sciences"),
	("SSC", "Social Sciences"),
	("SWK", "Social Work"),
	("SOC", "Sociology"),
	("SPA", "Spanish"),
	("SES", "Specialized Education Services"),
	("STA", "Statistics"),
	("SCM", "Supply Chain Management"),
	("TED", "Teacher Education"),
	("THR", "Theatre"),
	("UNCX", "UNC Exchange"),
	("LIB", "University Libraries"),
	("VPA", "Visual and Performing Arts"),
	("WCV", "Western Civilization"),
	("WGS", "Women's, Gender, and Sexuality Studies");